In [3]:
import pandas as pd
import numpy as np

In [4]:
years = [2015, 2016, 2017, 2018]
years

[2015, 2016, 2017, 2018]

In [5]:
years = list(range(2015, 2019 + 1))
years

[2015, 2016, 2017, 2018, 2019]

In [6]:
name = "Jan Kowalski"
print(name[0]) # pierwsza litera
print(name[-1]) # ostatnia litera
print(name.lower()) # małe litery
print(name.upper()) # duże litery
print(name.split(' ')) # rozdziel string na listę używając danego separatora (w tym przypadku jest to spacja)

J
i
jan kowalski
JAN KOWALSKI
['Jan', 'Kowalski']


In [7]:
years = range(2010, 2019)
print([year for year in years])
print([year * 2 for year in years])
print([year * 2 for year in years if year % 2 == 0])

[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
[4020, 4022, 4024, 4026, 4028, 4030, 4032, 4034, 4036]
[4020, 4024, 4028, 4032, 4036]


In [8]:
[x - 50 for x in years]

[1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968]

In [15]:
output = []
for year in years:
    if year % 2 == 0:
        output.append(year * 2)
output

[4020, 4024, 4028, 4032, 4036]

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6]) # tablica
print(arr)
type(arr)

[1 2 3 4 5 6]


numpy.ndarray

In [21]:
print(arr == 1)
print(arr == 2)
print(arr > 2)
print(arr %2 == 0)

[ True False False False False False]
[False  True False False False False]
[False False  True  True  True  True]
[False  True False  True False  True]


In [22]:
arr[ arr % 2 == 0 ]

array([2, 4, 6])

In [18]:
np.array([1, 2, 3]) + np.array([5, 6, 7])

array([ 6,  8, 10])

In [19]:
np.mean([1, 2, 3])

np.float64(2.0)

In [20]:
np.array([1, 2, 3]).mean()

np.float64(2.0)

In [23]:
lista = list(range(0, 19))
print([id for id in lista if id % 4 == 0])

[0, 4, 8, 12, 16]


In [24]:
my_arr = np.arange(0, 19)
print([x for x in my_arr if x % 4 == 0])

[np.int64(0), np.int64(4), np.int64(8), np.int64(12), np.int64(16)]


In [25]:
list_a = np.array(range(0, 19))
list_b = np.array(range(-19, 0))

list_c = list_a + list_b
list_c
np.median(list_c)

np.float64(-1.0)

In [30]:
my_list = np.arange(1000)
frst = (my_list >= 50) & (my_list < 100)
scnd = (my_list >= 325) & (my_list <= 388)

my_list [frst|scnd]

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 325, 326,
       327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
       340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
       353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
       366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378,
       379, 380, 381, 382, 383, 384, 385, 386, 387, 388])

In [36]:
x = np.arange(1000)
x2 = x[50:100]
x3 = x[325:389]

result = np.union1d(x2, x3)
result

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 325, 326,
       327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
       340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
       353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
       366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378,
       379, 380, 381, 382, 383, 384, 385, 386, 387, 388])

In [38]:
np.random.seed(1)
rows = 15

df = pd.DataFrame({
    'height': np.random.randint(140, 210, rows),
    'weight': np.random.randint(50, 80, rows),
})

df

height  weight
0      177      64
1      152      68
2      149      54
3      145      73
4      204      73
5      156      59
6      141      67
7      146      73
8      165      50
9      190      72
10     160      63
11     158      59
12     151      59
13     168      57
14     169      79

In [39]:
df.height
df['height']

0     177
1     152
2     149
3     145
4     204
5     156
6     141
7     146
8     165
9     190
10    160
11    158
12    151
13    168
14    169
Name: height, dtype: int64

In [40]:
df['ratio'] = df['height'] / df['weight']
df.head()

height  weight     ratio
0     177      64  2.765625
1     152      68  2.235294
2     149      54  2.759259
3     145      73  1.986301
4     204      73  2.794521

In [41]:
df[ (df.height < 145) | (df.height > 195) ]

height  weight     ratio
4     204      73  2.794521
6     141      67  2.104478

In [42]:
if 'ratio' in df: del df['ratio']